package com.sanadedu.parent.student.data.dto

import com.sanadedu.parent.feed.domain.dto.MetadataDTO

data class ExamsResponse(
    val status: String,
    val data: List<ExamDTO>,
    val metadata: MetadataDTO
)

data class ExamDTO(
    val _id: String,
    val tutorCourse: String,
    val tutor: String,
    val title: String,
    val examNumber: Int,
    val type: String,
    val durationInMinutes: Int,
    val topics: List<String>,
    val sessions: List<String>,
    val startTime: String,
    val endTime: String,
    val isAutoGenerated: Boolean,
    val totalQuestions: Int,
    val createdBy: CreatedByDTO,
    val expectedMark: Int,
    val totalMark: Int,
    val totalStudents: Int,
    val createdAt: String,
    val updatedAt: String,
    val __v: Int,
    val topicData: List<TopicDataDTO>,
    val grade: Int
)

data class TopicDataDTO(
    val _id: String,
    val name: String,
    val color: String
)